### PR TITLE
Logs enhancement

### LINKED ISSUE #487: Cryptic errors in some situations
related to https://github.com/src-d/lookout/issues/486

There are some situations that cause unhandled errors like the following one. 
```shell
[2019-01-23T11:17:34.461935361+01:00] ERROR event processing failed 
app=lookoutd 
error=posting analysis failed: %!s(PANIC=runtime error: invalid memory address or nil pointer dereference) 
event-id=b44c158d09bebb40b85ce23763dd9ab179926019 
event-type=*pb.ReviewEvent 
github.pr=63 
head=refs/pull/63/head 
repo=https://github.com/dpordomingo/testing-repo.git
```
When it happens, it's difficult to know what's causing the error.
In this case, I found that it was related to https://github.com/google/go-github/issues/540 

It would be a good idea to provide more details in those logs.

### PR DESCRIPTION
**Pull request by dpordomingo**
fix #487

### before:
```shell
ERROR event processing failed
app=lookout
event-id=b44c158d09bebb40b85ce23763dd9ab179926019
event-type=*pb.ReviewEvent
github.pr=63
head=refs/pull/63/head
repo=https://github.com/dpordomingo/testing-repo.git
error=posting analysis failed: %!s(PANIC=runtime error: invalid memory address or nil pointer 
```
**problems:**
- no info about what caused the error
- error message is a `PANIC` without trace

### after
```shell
ERROR event processing failed

.... (same data as before changes)

error=posting analysis failed: github api error: review could not be pushed:
    POST https://api.github.com/repos/dpordomingo/testing-repo/pulls/63/reviews
    422 Unprocessable Entity
    [{Resource:Review
      Message:Path is invalid
    }]
```
**benefits:**
- error message contains where was caused the problem
  - GitHub API endpoint
  - GitHub API real error message 

these :point_up: new details would have been really useful when debugging https://github.com/src-d/lookout/issues/486

**cons:**
- the workaround done inside [`handleAPIError`](https://github.com/src-d/lookout/pull/488/files#diff-15bfbf8e99100aba04e081d16e13036bR419) could be done directly in `google/go-github` project, but it should be considered separately, so I'd handle it in [a google/go-github PR](https://github.com/dpordomingo/go-github/pull/1/files#diff-9bd6c2575adb220521a096df92e2d502R659)

### CODE REVIEW

File: provider/github/review.go [hunk 1]
```diff
@@ -99,7 +134,7 @@ func getPostedComment(ctx context.Context, client *Client, owner, repo string, n
 	var reviews []*github.PullRequestReview
 	for {
 		rs, resp, err := client.PullRequests.ListReviews(ctx, owner, repo, number, listReviewsOpts)
-		if handleAPIError(resp, err) != nil {
+		if handleAPIError(resp, err, "pull request reviews could not listed") != nil {
```
Comment (carlosms) [inline provider/github/review.go]:
```suggestion
		if handleAPIError(resp, err, "pull request reviews could not be listed") != nil {
```

File: provider/github/review.go [hunk 2]
```diff
@@ -118,7 +153,7 @@ func getPostedComment(ctx context.Context, client *Client, owner, repo string, n
 
 		for {
 			comments, resp, err := client.PullRequests.ListReviewComments(ctx, owner, repo, int64(number), review.GetID(), listCommentsOpts)
-			if handleAPIError(resp, err) != nil {
+			if handleAPIError(resp, err, "review comments could not list") != nil {
```
Comment (carlosms) [inline provider/github/review.go]:
```suggestion
			if handleAPIError(resp, err, "review comments could not be listed") != nil {
```

File: provider/github/review.go [hunk 3]
```diff
@@ -40,7 +40,11 @@ func createReview(
 	requests := splitReviewRequest(req, batchReviewComments)
 	for i, req := range requests {
 		_, resp, err := client.PullRequests.CreateReview(ctx, owner, repo, number, req)
-		if err = handleAPIError(resp, err); err != nil {
+
+		if err = handleAPIError(resp, err, "review could not be pushed"); err != nil {
+			ctxlog.WithLogFields(ctx, log.Fields{
```
Comment (carlosms) [inline provider/github/review.go]: is this line doing anything? you don't use the returned ctx or logger.

Comment (dpordomingo) [reply provider/github/review.go]: This line is adding the comments to the logger `Fields`, so they will appear later when performing the real `Errorf` at [server/server.go::L114](https://github.com/src-d/lookout/pull/488/files#diff-91bbeda7eb98a7adc57b9e47e2cf5c2bR114).

An alternative could be to get the logger `Fields` and append this new one (but when doing so, tests didn't pass because of a `nil` dereference, and I didn't want o try harder)

Comment (carlosms) [reply provider/github/review.go]: I've tested your branch and yes, your code is working but it shouldn't :sweat_smile: 
The original `ctx` log fields should not be modified... https://github.com/src-d/lookout/issues/491

Comment (dpordomingo) [reply provider/github/review.go]: fair enough. Since I didn't want to block this enhancement till we have an agreement on how to add content to the error, we can follow that in a separate PR.

**Comment by dpordomingo** [comment]
As I said https://github.com/src-d/lookout/pull/488#discussion_r251038793 I moved the disputed commit to a new PR https://github.com/src-d/lookout/pull/492 so the enhancements proposed by this one wont be blocked :dagger:

File: server/server.go [hunk 4]
```diff
@@ -110,7 +110,8 @@ func (s *Server) HandleEvent(ctx context.Context, e lookout.Event) error {
 	if err == nil {
 		status = models.EventStatusProcessed
 	} else {
-		logger.Errorf(err, "event processing failed")
+
+		ctxlog.Get(ctx).Errorf(err, "event processing failed")
```
Comment (carlosms) [inline server/server.go]: After extracting the commits to #492, I think this change is not needed anymore

Comment (dpordomingo) [reply server/server.go]: that's true

File: provider/github/watcher.go [hunk 5]
```diff
@@ -333,7 +333,7 @@ func (w *Watcher) doEventRequest(ctx context.Context, client *Client, username,
 	)
 
 	if err != nil {
-		return resp, nil, ErrGitHubAPI.Wrap(err)
+		return resp, nil, ErrGitHubAPI.Wrap(err, "events repository could not be listed")
```
Comment (carlosms) [inline provider/github/watcher.go]:
```suggestion
		return resp, nil, ErrGitHubAPI.Wrap(err, "repository events could not be listed")
```

**Comment by dpordomingo** [comment]
I have no clue about why integration tests are now failing...

**Comment by dpordomingo** [comment]
I saw it's already failing in `master` since last Friday
https://travis-ci.org/src-d/lookout/builds/484454336

**Comment by dpordomingo** [comment]
And it is now passing.
https://travis-ci.org/src-d/lookout/builds/485567163
Heisenbug?
image

**Comment by carlosms** [comment]
It's probably because of #490.
