### PR TITLE
Fix default auth

### LINKED ISSUE #157: Github env vars are not used
If individual `user` & `token` are not set in the `config.yml` file the log says `use default token for repository`.

But what is actually happening is that the requests are made without any authorization, `GITHUB_USER` & `_TOKEN` env vars are not used.

This is the problem blocking https://github.com/src-d/lookout/issues/80 & https://github.com/src-d/issues-infrastructure/issues/213

### PR DESCRIPTION
**Pull request by carlosms**
Fix #157.

The bug was checking zero value with 2 pointers, instead of values.
I also moved the default auth management to `serve.go`, I think it simplifies it and make it easier to understanding.

### CODE REVIEW

File: cmd/lookout/serve.go [hunk 1]
```diff
@@ -141,6 +141,12 @@ func (c *ServeCommand) Execute(args []string) error {
 }
 
 func (c *ServeCommand) initProvider(conf Config) error {
+	noDeafultAuth := c.GithubUser == "" || c.GithubToken == ""
```
Comment (smacker) [inline cmd/lookout/serve.go]: noDeafultAuth -> noDefaultAuth

File: cmd/lookout/serve.go [hunk 2]
```diff
@@ -155,16 +161,21 @@ func (c *ServeCommand) initProvider(conf Config) error {
 		for _, url := range urls {
 			conf, ok := repoToConfig[url]
 			if !ok {
-				log.Infof("use default token for repository %s", url)
+				if noDeafultAuth {
+					// Empty github auth is only useful for --dry-run,
+					// we may want to enforce this as an error
+					log.Warningf("missing authentication for repository %s, and no default provided", url)
```
Comment (smacker) [inline cmd/lookout/serve.go]: 👍
