### PR TITLE
Fixes timeouts in tests due to OS limitation

### LINKED ISSUE #537: Failing test TestServerTestSuite/TestPushTimeout
Failing on master (626408f), from travis logs on `make coverage`
```
    --- FAIL: TestServerTestSuite/TestPushTimeout (0.01s)
        require.go:738: 
            	Error Trace:	server_test.go:173
            	Error:      	"[text:"base-hash > head-hash" ]" should have 0 item(s), but has 1
            	Test:       	TestServerTestSuite/TestPushTimeout
```

The tests passed after a travis job restart.

### PR DESCRIPTION
**Pull request by se7entyse7en**
Closes #537.

### CODE REVIEW

File: server/server_test.go [hunk 1]
```diff
@@ -119,8 +119,8 @@ func (s *ServerTestSuite) TestPush() {
 func (s *ServerTestSuite) TestReviewTimeout() {
 	require := s.Require()
 
-	reviewSleep, _ := time.ParseDuration("5ms")
-	reviewTimeout, _ := time.ParseDuration("1ms")
+	reviewSleep := 1 * time.Second
```
Comment (smacker) [inline server/server_test.go]: that is very huge timeout. I understand 5ms can be too small but for example 100ms or 200ms?
This change slows down tests a lot which isn't cool when you use them to validate the code...

**Comment by se7entyse7en** [comment]
@smacker used 100ms and 200ms 👍
